name: leplens_python
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - ipykernel=6.19.2
  - ipython=8.15.0
  - jedi=0.18.1
  - jupyter_client=7.2.2
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - openssl=1.1.1w
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=22.3.0
  - readline=8.1.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.7.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - pip:
      - absl-py==2.0.0
      - asttokens==2.0.5
      - astunparse==1.6.3
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - executing==0.8.3
      - flatbuffers==23.5.26
      - fonttools==4.44.0
      - gast==0.5.4
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - h5py==3.10.0
      - idna==3.4
      - keras==2.14.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - matplotlib==3.8.1
      - ml-dtypes==0.2.0
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - pandas==2.1.3
      - pillow==10.1.0
      - protobuf==4.25.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - urllib3==2.1.0
      - wcwidth==0.2.5
      - werkzeug==3.0.1
      - wrapt==1.14.1
